"""update review  table

Revision ID: 830707266ba4
Revises: fa629703687b
Create Date: 2025-10-09 13:09:55.577549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '830707266ba4'
down_revision: Union[str, Sequence[str], None] = 'fa629703687b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('reviews', sa.Column('username', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'username')
    op.drop_column('reviews', 'created_at')
    # ### end Alembic commands ###
