"""Add single system_settings table

Revision ID: 883cf508e610
Revises: 9ad07c6fadfa
Create Date: 2025-10-07 13:27:13.046574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '883cf508e610'
down_revision: Union[str, Sequence[str], None] = '9ad07c6fadfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('borrow_day_limit', sa.Integer(), nullable=False),
    sa.Column('borrow_extend_limit', sa.Integer(), nullable=False),
    sa.Column('borrow_limit', sa.Integer(), nullable=False),
    sa.Column('booking_duration', sa.Integer(), nullable=False),
    sa.Column('booking_days_limit', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_table('system_settings')
    # ### end Alembic commands ###
