"""update book  table

Revision ID: bb44ca0693e4
Revises: cc6ab018ef2a
Create Date: 2025-10-06 14:56:26.693822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb44ca0693e4'
down_revision: Union[str, Sequence[str], None] = 'cc6ab018ef2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('books', sa.Column('pdf', sa.String(length=255), nullable=True))
    op.add_column('books', sa.Column('audio', sa.String(length=255), nullable=True))
    op.add_column('donation_books', sa.Column('pdf', sa.String(), nullable=True))
    op.add_column('donation_books', sa.Column('audio', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('donation_books', 'audio')
    op.drop_column('donation_books', 'pdf')
    op.drop_column('books', 'audio')
    op.drop_column('books', 'pdf')
    op.drop_column('books', 'created_at')
    # ### end Alembic commands ###
